In [4]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler 
from sklearn.impute import SimpleImputer
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [8]:
x, y = make_classification(n_samples=100, n_features=20)

In [10]:
x

array([[-0.06236069,  0.29675596,  0.03197083, ..., -1.30917329,
         1.03202729,  0.84435464],
       [ 0.18237176, -0.00664097,  0.05007739, ..., -0.48822006,
         0.31410038, -1.24848233],
       [ 0.63031897,  1.53160847,  0.43224423, ..., -0.01927503,
        -2.12430195,  0.36285973],
       ...,
       [ 0.35196909, -0.40999011,  0.0304332 , ..., -0.60991776,
        -0.25170609, -0.89411731],
       [ 0.57722472, -0.53512493,  0.07279196, ...,  0.04030447,
        -0.57996359,  1.87133659],
       [-1.02898726, -0.03019283, -0.2938295 , ...,  1.21203278,
         0.47739486, -0.78193448]])

In [11]:
y

array([1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [16]:
x = pd.DataFrame(x)
x

0         1         2         3         4         5         6   \
0  -0.062361  0.296756  0.031971 -1.960224 -0.952174  1.483099  2.350522   
1   0.182372 -0.006641  0.050077  0.159020 -0.234140  0.285567  0.772372   
2   0.630319  1.531608  0.432244 -1.131182  0.881178  0.181435 -1.249894   
3  -2.138318  1.862692 -0.289607 -0.587042  0.252371 -0.046548 -1.056792   
4   0.704634  1.070426  0.376217  0.008685  0.404939  0.260721 -0.324749   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.736645  1.091005  0.388631 -0.148454  0.095644  0.708789  0.316977   
96  1.889937 -2.054289  0.187954 -0.629938 -0.586324 -0.499869 -0.409360   
97  0.351969 -0.409990  0.030433 -0.364506  0.292012 -0.079007  1.205633   
98  0.577225 -0.535125  0.072792 -0.142268 -1.165630 -0.672772  0.803164   
99 -1.028987 -0.030193 -0.293829 -0.290397 -0.482321 -0.936225 -0.593945   

          7         8         9         10        11        12        13  \
0   2.017496  0.696902 -0.554133 -0.850936 -0.325495 -1.217044  2.810788   
1  -0.239879  1.874200  0.074794  1.852585 -0.277479 -0.939860 -0.132349   
2  -0.495364 -1.318433  0.097377  0.708391 -0.614443  0.813700  0.541496   
3  -0.587429  0.904659  2.111410 -0.343021  0.423495  0.258827  0.262246   
4   0.318168 -0.802757  1.061723  0.099998 -0.056259 -1.982539  0.610759   
..       ...       ...       ...       ...       ...       ...       ...   
95 -2.754516 -0.344014 -0.874561  0.264807  0.400471  1.230138  0.452597   
96 -0.978918  1.254367  0.356681  0.433240 -0.043936 -0.688410 -1.181470   
97  0.896056  1.230019  0.211571 -0.486039 -0.843954  1.350798 -2.143403   
98  1.481302  1.021403 -0.283069  1.544469 -0.759819 -1.168462 -0.852285   
99 -1.221182  0.280353 -1.165813  1.256511  0.186225  0.629664  1.116064   

          14        15        16        17        18        19  
0   0.529383  0.095788  0.351458 -1.309173  1.032027  0.844355  
1  -0.834265  1.417437 -0.183968 -0.488220  0.314100 -1.248482  
2   0.517712 -0.828872  0.887405 -0.019275 -2.124302  0.362860  
3   2.063141  1.192794  3.905895 -1.641951  1.179078  1.043650  
4  -0.908971  0.169665  0.363200 -1.977506 -0.002401  0.164616  
..       ...       ...       ...       ...       ...       ...  
95  0.527851 -1.242563  0.352216  0.492877 -0.447979  0.317820  
96 -0.071194 -0.212929 -3.851940 -0.533395 -0.056173  1.831730  
97  0.120172  0.178465 -0.744220 -0.609918 -0.251706 -0.894117  
98  0.478219  0.562967 -1.086023  0.040304 -0.579964  1.871337  
99 -0.124356  0.759575  0.971692  1.212033  0.477395 -0.781934  

[100 rows x 20 columns]

In [15]:
y = pd.DataFrame(y)
y

0
0   1
1   1
2   1
3   0
4   1
.. ..
95  1
96  1
97  0
98  1
99  0

[100 rows x 1 columns]

In [17]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       100 non-null    float64
 1   1       100 non-null    float64
 2   2       100 non-null    float64
 3   3       100 non-null    float64
 4   4       100 non-null    float64
 5   5       100 non-null    float64
 6   6       100 non-null    float64
 7   7       100 non-null    float64
 8   8       100 non-null    float64
 9   9       100 non-null    float64
 10  10      100 non-null    float64
 11  11      100 non-null    float64
 12  12      100 non-null    float64
 13  13      100 non-null    float64
 14  14      100 non-null    float64
 15  15      100 non-null    float64
 16  16      100 non-null    float64
 17  17      100 non-null    float64
 18  18      100 non-null    float64
 19  19      100 non-null    float64
dtypes: float64(20)
memory usage: 15.8 KB


In [18]:
x.describe()

0           1           2           3           4           5   \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.053941    0.061170    0.025337    0.033579   -0.023790    0.183331   
std      1.260440    1.062604    0.388543    0.918384    0.939410    0.891984   
min     -2.517499   -2.210142   -0.888817   -2.027586   -2.793503   -1.825041   
25%     -0.841880   -0.768049   -0.161703   -0.583761   -0.669926   -0.337121   
50%     -0.048315    0.324877    0.019255    0.008637   -0.083002    0.165282   
75%      0.710953    0.941401    0.156183    0.520868    0.639878    0.735607   
max      3.810017    1.862692    1.264133    2.250492    1.718527    2.381914   

               6           7           8           9           10          11  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.063607   -0.025572    0.130865   -0.186528    0.026773   -0.016259   
std      1.061405    1.106696    1.049811    0.893688    0.830322    0.971999   
min     -2.693573   -2.754516   -2.679738   -2.463025   -1.834261   -2.243137   
25%     -0.646452   -0.722325   -0.512360   -0.805401   -0.634608   -0.668524   
50%     -0.034263   -0.023254    0.177001   -0.173709    0.097879   -0.048458   
75%      0.706488    0.495915    0.911850    0.326109    0.619617    0.591032   
max      3.599870    3.544737    2.520941    2.430741    1.852585    2.145732   

               12          13          14          15          16          17  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean    -0.128227    0.019415   -0.034029   -0.022965    0.007450   -0.155480   
std      0.976997    0.935284    1.006373    1.053086    1.643676    0.919419   
min     -2.774632   -2.143403   -2.858731   -2.732852   -3.851940   -2.329135   
25%     -0.711786   -0.602924   -0.706934   -0.680883   -0.917928   -0.777918   
50%     -0.028567   -0.129979   -0.071525    0.118710    0.026677   -0.216814   
75%      0.577834    0.516576    0.634332    0.631789    1.202541    0.499786   
max      2.268320    2.810788    2.506902    2.457502    3.905895    2.293522   

               18          19  
count  100.000000  100.000000  
mean     0.063524   -0.009513  
std      1.003488    1.027155  
min     -2.383703   -3.079075  
25%     -0.645441   -0.642591  
50%      0.039288   -0.038373  
75%      0.862865    0.684874  
max      2.742608    2.722933

In [19]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       100 non-null    int64
dtypes: int64(1)
memory usage: 928.0 bytes


In [20]:
y.describe()

0
count  100.000000
mean     0.500000
std      0.502519
min      0.000000
25%      0.000000
50%      0.500000
75%      1.000000
max      1.000000

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [27]:
x_train.shape, x_test.shape

((70, 20), (30, 20))

# Classifiers 

Decision Tree Classifier

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
first_classifier = DecisionTreeClassifier()

In [28]:
first_classifier.fit(x_train, y_train)

DecisionTreeClassifier()

In [29]:
y_pred = first_classifier.predict(x_test)

In [30]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1])

In [32]:
from sklearn.metrics import accuracy_score

In [36]:
print(f'Accuracy using Decision Tree Classifier : {accuracy_score(y_true=y_test, y_pred=y_pred)}')

Accuracy using Decision Tree Classifier : 0.8333333333333334


In [37]:
from sklearn.svm import SVC

In [38]:
clf = SVC()

In [39]:
clf.fit(x_train, y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [40]:
y_pred = clf.predict(x_test)

In [43]:
print(f'Accuracy using SVC is : {accuracy_score(y_true=y_test, y_pred=y_pred)}')

Accuracy using SVC is : 0.8


In [44]:
from sklearn.ensemble import RandomForestClassifier

In [45]:
clf = RandomForestClassifier()

In [46]:
clf.fit(x_train, y_train)

/tmp/ipykernel_33/3292451027.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(x_train, y_train)


RandomForestClassifier()

In [47]:
y_pred = clf.predict(x_test)

In [49]:
print(f'accuracy score using Random Forest is: {accuracy_score(y_true=y_test, y_pred=y_pred)}')

accuracy score using Random Forest is: 0.9666666666666667


In [50]:
from sklearn.ensemble import GradientBoostingClassifier

In [51]:
clf = GradientBoostingClassifier()

In [52]:
clf.fit(x_train, y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier()

In [53]:
y_pred = clf.predict(x_test)

In [54]:
y_pred

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0])

In [55]:
accuracy_score(y_true=y_test, y_pred=y_pred)

0.8

In [56]:
from sklearn.linear_model import LogisticRegression

In [57]:
clf = LogisticRegression()

In [58]:
clf.fit(x_train, y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [59]:
y_pred = clf.predict(x_test)

In [60]:
y_pred 

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0])

In [62]:
print(f'Accuracy score using LR is : {accuracy_score(y_true=y_test, y_pred=y_pred)}')

Accuracy score using LR is : 0.9
